version: "3.8"

services:
  postgres:
    image: postgres:17-alpine
    container_name: notes-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: notes_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
